# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atasamMeteosat.ui'
#
# Created: Wed Jul 31 16:01:10 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1046, 630)
        Form.setMinimumSize(QtCore.QSize(1046, 630))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/cam.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.graphicsView = QtGui.QGraphicsView(self.tab_3)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_14.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.listWidget = QtGui.QListWidget(self.tab_3)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_14.addWidget(self.listWidget, 0, 1, 1, 4)
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_14.addWidget(self.label, 1, 2, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_3)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBox, 1, 3, 1, 2)
        self.progressBar = QtGui.QProgressBar(self.tab_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_14.addWidget(self.progressBar, 2, 0, 1, 2)
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_14.addWidget(self.pushButton_2, 2, 2, 1, 2)
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_14.addWidget(self.pushButton, 2, 4, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.tab_5)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.gridLayout_4.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(self.tab_5)
        self.listWidget_2.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_4.addWidget(self.listWidget_2, 0, 1, 1, 4)
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.tab_5)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_2, 1, 3, 1, 2)
        self.progressBar_2 = QtGui.QProgressBar(self.tab_5)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_4.addWidget(self.progressBar_2, 2, 0, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(self.tab_5)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 2, 1, 2)
        self.pushButton_4 = QtGui.QPushButton(self.tab_5)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_4.addWidget(self.pushButton_4, 2, 4, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.graphicsView_3 = QtGui.QGraphicsView(self.tab_4)
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.gridLayout_5.addWidget(self.graphicsView_3, 0, 0, 1, 1)
        self.listWidget_3 = QtGui.QListWidget(self.tab_4)
        self.listWidget_3.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.gridLayout_5.addWidget(self.listWidget_3, 0, 1, 1, 4)
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 1, 2, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.tab_4)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_3, 1, 3, 1, 2)
        self.progressBar_3 = QtGui.QProgressBar(self.tab_4)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.gridLayout_5.addWidget(self.progressBar_3, 2, 0, 1, 2)
        self.pushButton_5 = QtGui.QPushButton(self.tab_4)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_5.addWidget(self.pushButton_5, 2, 2, 1, 2)
        self.pushButton_6 = QtGui.QPushButton(self.tab_4)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_5.addWidget(self.pushButton_6, 2, 4, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_6)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.graphicsView_4 = QtGui.QGraphicsView(self.tab_7)
        self.graphicsView_4.setObjectName(_fromUtf8("graphicsView_4"))
        self.gridLayout_15.addWidget(self.graphicsView_4, 0, 0, 1, 1)
        self.listWidget_4 = QtGui.QListWidget(self.tab_7)
        self.listWidget_4.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_4.setObjectName(_fromUtf8("listWidget_4"))
        self.gridLayout_15.addWidget(self.listWidget_4, 0, 1, 1, 4)
        self.label_4 = QtGui.QLabel(self.tab_7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_15.addWidget(self.label_4, 1, 2, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.tab_7)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_15.addWidget(self.comboBox_4, 1, 3, 1, 2)
        self.progressBar_4 = QtGui.QProgressBar(self.tab_7)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setObjectName(_fromUtf8("progressBar_4"))
        self.gridLayout_15.addWidget(self.progressBar_4, 2, 0, 1, 2)
        self.pushButton_7 = QtGui.QPushButton(self.tab_7)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_15.addWidget(self.pushButton_7, 2, 2, 1, 2)
        self.pushButton_8 = QtGui.QPushButton(self.tab_7)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_15.addWidget(self.pushButton_8, 2, 4, 1, 1)
        self.tabWidget_3.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.graphicsView_5 = QtGui.QGraphicsView(self.tab_8)
        self.graphicsView_5.setObjectName(_fromUtf8("graphicsView_5"))
        self.gridLayout_6.addWidget(self.graphicsView_5, 0, 0, 1, 1)
        self.listWidget_5 = QtGui.QListWidget(self.tab_8)
        self.listWidget_5.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.gridLayout_6.addWidget(self.listWidget_5, 0, 1, 1, 4)
        self.label_5 = QtGui.QLabel(self.tab_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 2, 1, 1)
        self.comboBox_5 = QtGui.QComboBox(self.tab_8)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboBox_5, 1, 3, 1, 2)
        self.progressBar_5 = QtGui.QProgressBar(self.tab_8)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setObjectName(_fromUtf8("progressBar_5"))
        self.gridLayout_6.addWidget(self.progressBar_5, 2, 0, 1, 2)
        self.pushButton_9 = QtGui.QPushButton(self.tab_8)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_6.addWidget(self.pushButton_9, 2, 2, 1, 2)
        self.pushButton_10 = QtGui.QPushButton(self.tab_8)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_6.addWidget(self.pushButton_10, 2, 4, 1, 1)
        self.tabWidget_3.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_9)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.graphicsView_6 = QtGui.QGraphicsView(self.tab_9)
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.gridLayout_8.addWidget(self.graphicsView_6, 0, 0, 1, 1)
        self.listWidget_6 = QtGui.QListWidget(self.tab_9)
        self.listWidget_6.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_6.setObjectName(_fromUtf8("listWidget_6"))
        self.gridLayout_8.addWidget(self.listWidget_6, 0, 1, 1, 4)
        self.label_6 = QtGui.QLabel(self.tab_9)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_8.addWidget(self.label_6, 1, 2, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.tab_9)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBox_6, 1, 3, 1, 2)
        self.progressBar_6 = QtGui.QProgressBar(self.tab_9)
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setObjectName(_fromUtf8("progressBar_6"))
        self.gridLayout_8.addWidget(self.progressBar_6, 2, 0, 1, 2)
        self.pushButton_11 = QtGui.QPushButton(self.tab_9)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_8.addWidget(self.pushButton_11, 2, 2, 1, 2)
        self.pushButton_12 = QtGui.QPushButton(self.tab_9)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_8.addWidget(self.pushButton_12, 2, 4, 1, 1)
        self.tabWidget_3.addTab(self.tab_9, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_4 = QtGui.QTabWidget(self.tab_2)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_10)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.graphicsView_7 = QtGui.QGraphicsView(self.tab_10)
        self.graphicsView_7.setObjectName(_fromUtf8("graphicsView_7"))
        self.gridLayout_16.addWidget(self.graphicsView_7, 0, 0, 1, 1)
        self.listWidget_7 = QtGui.QListWidget(self.tab_10)
        self.listWidget_7.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_7.setObjectName(_fromUtf8("listWidget_7"))
        self.gridLayout_16.addWidget(self.listWidget_7, 0, 1, 1, 4)
        self.label_7 = QtGui.QLabel(self.tab_10)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_16.addWidget(self.label_7, 1, 2, 1, 1)
        self.comboBox_7 = QtGui.QComboBox(self.tab_10)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout_16.addWidget(self.comboBox_7, 1, 3, 1, 2)
        self.progressBar_7 = QtGui.QProgressBar(self.tab_10)
        self.progressBar_7.setProperty("value", 0)
        self.progressBar_7.setObjectName(_fromUtf8("progressBar_7"))
        self.gridLayout_16.addWidget(self.progressBar_7, 2, 0, 1, 2)
        self.pushButton_13 = QtGui.QPushButton(self.tab_10)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_16.addWidget(self.pushButton_13, 2, 2, 1, 2)
        self.pushButton_14 = QtGui.QPushButton(self.tab_10)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_16.addWidget(self.pushButton_14, 2, 4, 1, 1)
        self.tabWidget_4.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_11)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.graphicsView_8 = QtGui.QGraphicsView(self.tab_11)
        self.graphicsView_8.setObjectName(_fromUtf8("graphicsView_8"))
        self.gridLayout_9.addWidget(self.graphicsView_8, 0, 0, 1, 1)
        self.listWidget_8 = QtGui.QListWidget(self.tab_11)
        self.listWidget_8.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_8.setObjectName(_fromUtf8("listWidget_8"))
        self.gridLayout_9.addWidget(self.listWidget_8, 0, 1, 1, 4)
        self.label_8 = QtGui.QLabel(self.tab_11)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_9.addWidget(self.label_8, 1, 2, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.tab_11)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout_9.addWidget(self.comboBox_8, 1, 3, 1, 2)
        self.progressBar_8 = QtGui.QProgressBar(self.tab_11)
        self.progressBar_8.setProperty("value", 0)
        self.progressBar_8.setObjectName(_fromUtf8("progressBar_8"))
        self.gridLayout_9.addWidget(self.progressBar_8, 2, 0, 1, 2)
        self.pushButton_15 = QtGui.QPushButton(self.tab_11)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_9.addWidget(self.pushButton_15, 2, 2, 1, 2)
        self.pushButton_16 = QtGui.QPushButton(self.tab_11)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_9.addWidget(self.pushButton_16, 2, 4, 1, 1)
        self.tabWidget_4.addTab(self.tab_11, _fromUtf8(""))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_12)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.graphicsView_9 = QtGui.QGraphicsView(self.tab_12)
        self.graphicsView_9.setObjectName(_fromUtf8("graphicsView_9"))
        self.gridLayout_10.addWidget(self.graphicsView_9, 0, 0, 1, 1)
        self.listWidget_9 = QtGui.QListWidget(self.tab_12)
        self.listWidget_9.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_9.setObjectName(_fromUtf8("listWidget_9"))
        self.gridLayout_10.addWidget(self.listWidget_9, 0, 1, 1, 4)
        self.label_9 = QtGui.QLabel(self.tab_12)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 1, 2, 1, 1)
        self.comboBox_9 = QtGui.QComboBox(self.tab_12)
        self.comboBox_9.setObjectName(_fromUtf8("comboBox_9"))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.comboBox_9.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox_9, 1, 3, 1, 2)
        self.progressBar_9 = QtGui.QProgressBar(self.tab_12)
        self.progressBar_9.setProperty("value", 0)
        self.progressBar_9.setObjectName(_fromUtf8("progressBar_9"))
        self.gridLayout_10.addWidget(self.progressBar_9, 2, 0, 1, 2)
        self.pushButton_17 = QtGui.QPushButton(self.tab_12)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_10.addWidget(self.pushButton_17, 2, 2, 1, 2)
        self.pushButton_18 = QtGui.QPushButton(self.tab_12)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_10.addWidget(self.pushButton_18, 2, 4, 1, 1)
        self.tabWidget_4.addTab(self.tab_12, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(Form)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Atasam Meteosat", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setFormat(QtGui.QApplication.translate("Form", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "MSG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "MSGRSS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_3.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "MPF", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Avrasya", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_4.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QtGui.QApplication.translate("Form", "MSG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_5.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QtGui.QApplication.translate("Form", "MSGRSS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_6.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QtGui.QApplication.translate("Form", "MPF", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("Form", "Dag", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_7.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), QtGui.QApplication.translate("Form", "MSG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_8.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_16.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), QtGui.QApplication.translate("Form", "MSGRSS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Method", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(0, QtGui.QApplication.translate("Form", "Day Natural Colours", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(1, QtGui.QApplication.translate("Form", "Day Microphysical (Summer)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(2, QtGui.QApplication.translate("Form", "Day Microphysical (Winter)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(3, QtGui.QApplication.translate("Form", "Convective Storms", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(4, QtGui.QApplication.translate("Form", "Day Solar", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(5, QtGui.QApplication.translate("Form", "Night Microphysical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(6, QtGui.QApplication.translate("Form", "Dust", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(7, QtGui.QApplication.translate("Form", "Airmass", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(8, QtGui.QApplication.translate("Form", "24-hour Ash Microphysics", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_9.setItemText(9, QtGui.QApplication.translate("Form", "HRV Clouds", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_17.setText(QtGui.QApplication.translate("Form", "Refresh file lists", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_18.setText(QtGui.QApplication.translate("Form", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_12), QtGui.QApplication.translate("Form", "MPF", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Türkiye", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

